apiVersion: v1
kind: Service
metadata:
  name: sentio-birder-ai
  namespace: sentio-staging
spec:
  selector:
    app: sentio-birder-ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
