apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "18.1.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: postgres-passwords
      secretKeys:
        adminPasswordKey: postgres-password
        replicationPasswordKey: replication-password
    primary:
      persistence:
        enabled: true
        size: 8Gi
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
