apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.6.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
    preUpgradeChecker:
      jobEnabled: false
    csi:
      kubeletRootDir: /var/lib/kubelet
    defaultSettings:
      backupstorePollInterval: 300
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/lib/longhorn
      defaultDataLocality: best-effort
      replicaSoftAntiAffinity: false
      replicaAutoBalance: best-effort
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      upgradeChecker: false
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
      backupCompressionMethod: lz4
      backupConcurrentLimit: 2
      restoreConcurrentLimit: 2
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      allowNodeDrainWithLastHealthyReplica: false
    longhornManager:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    longhornDriver:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    longhornUI:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
