apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: "Europe/Berlin"
  # WEBPASSWORD removed - now using secret
  DNS1: "1.1.1.1"
  DNS2: "1.0.0.1"
  DNSSEC: "true"
  DNSMASQ_LISTENING: "all"
  VIRTUAL_HOST: "pihole.syslabs.dev"
  TEMPERATUREUNIT: "c"
  WEBUIBOXEDLAYOUT: "boxed"
  QUERY_LOGGING: "true"