apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: "Europe/Berlin"
  DNS1: "1.1.1.1"
  DNS2: "1.0.0.1"
  DNSSEC: "true"
  DNSMASQ_LISTENING: "all"
  VIRTUAL_HOST: "pihole.syslabs.dev"
  TEMPERATUREUNIT: "c"
  WEBUIBOXEDLAYOUT: "boxed"
  QUERY_LOGGING: "true"
  # Allow queries from your local network
  PIHOLE_DNS_: "192.168.2.0/24"