apiVersion: ENC[AES256_GCM,data:YH4=,iv:w+oFRHN4avHt9CmkUqgh+v12OTH5y0mFbljjTc0a5SQ=,tag:tIdvEMh8xEP2HGV8hiYL8w==,type:str]
kind: ENC[AES256_GCM,data:mamfui0f,iv:z7b1CX5OMCazlsxL8fDWvmz/LgOldodF0P0mblS/AGA=,tag:B+GXeQ1W68rJVTMrfUHZSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xFg7cdVVxjgdt47ggTaa,iv:2yKSpLnYtutrlHBR9pxg+OBoL5FwJglQt4+VsoT7l5Q=,tag:AfzuA7tiQhUWbCBYBGdfCQ==,type:str]
    namespace: ENC[AES256_GCM,data:TdAs9cDl,iv:6WQh6oxa/4xDWDzi3VFCtDahDMO7bG9q29d7j9LktHU=,tag:ayZEnS93f9vH9I5WgqmPZA==,type:str]
type: ENC[AES256_GCM,data:EHfRWch/,iv:N2CsTAEgQj9H2BpNN5nkc3e0O9wTifhhHYsjevwTYLk=,tag:LFNEsuBWSe8i1FuVpRn7nw==,type:str]
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:87jlFc5Em/dDrQ==,iv:yRFQzY3JMA/NLMDc9hGeSkSCH3r8zizYTAQezXssJU8=,tag:1w+K7uWCmrRhRgAmux99Ng==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQm95d290eEpRZTJCMkor
            UjBFOFQ2VXQ2V001ckR4YzBoRlU1TldaeTBjClVrM3ZWa1V1R2NPVldPMm1adFpm
            YzFBcVU3Rml1NDNuUTNRNXRHblRmbFkKLS0tIE5SeTdRN2hjM1Qzc25Tdy9HZDBx
            RVYrQ3MwWnR1U2l1NUtCRXhOOTdvVWMK+AwYqZd5kIbuGuMgalIozdX8qfA1ykZy
            fuC46RN82T/3+670t715w1AH9jK8GjekZP3Gy1ElDw2h3Hccw7Pm2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NGo3dDZETVNGL3BadTRH
            TlJoQXE3QnBNUmZibW1xNGErN3FsdUZWaWpnCmVtajVOOTlxOHRvdnlyZjVteGEx
            TXlzTFRQRVoxRkJ5RUhxUitVN3VFbDQKLS0tIFVWWTRZNU9rbFZyQ0hFZnFoTjVy
            UEF0UTkwYVM3Zmd1WUdTTHExRXBic00Kq5KdqfwWHz4N7nF3jLt0Y45aimnCDJjK
            Ab4RLGyPqmoHx8pKY6aRoWv3FdC+iAFGSlrmvQ8hDJcLgnoXfZKvHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T22:40:49Z"
    mac: ENC[AES256_GCM,data:nH4tXw+OEMBWdPxFIHtIzda6aHfYJlj68/2IQXsaOIVx0J8qOpScNuaALGZ/g0GdRi2C7ecbIqRpz53TGmF7C58/kBV2LDhJNIjxSofy35uCjqhh+TuSSoEE+nUvlWXbq4/+hI/zWTQmPsx0u7gg8Y2oY5MOhN+i/i0E2XBezBE=,iv:ZBR5+TVaIFwgXCVOp7Q5TnFs1TPaenhL2tgsu9Gw/Q8=,tag:29cCdKROWDdypaFEExkC6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
