apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
  values:
    strategy:
      type: Recreate
    ingress:
      enabled: false
    main:
      persistence:
        enabled: true
        size: 5Gi
        accessMode: ReadWriteOnce
