apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: n8n.syslabs.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - n8n.syslabs.dev
          secretName: n8n-tls
    persistence:
      enabled: true
      size: 5Gi
      accessModes:
        - ReadWriteOnce
