apiVersion: ENC[AES256_GCM,data:Sqw=,iv:MfhmTp3rKISzSwVXTz0M6CJLiQNTW2/2vChPoDqaZiM=,tag:Uhxd6N6/Zy4uRakPnGx4cA==,type:str]
kind: ENC[AES256_GCM,data:7JOILHgp,iv:/HZiBAbE4f7Gfg7P8Y+n88NcbXfC0GPFAn9NXr7Wbso=,tag:qx+uhyY08KNSC7wvg1twkA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6MLlUl1m/N1y4RYkJHzeNEs4C8Q=,iv:ilcszK6BtvmJKCuQpD8DBKJ7zZ6QhcQUrMDe+egBtRM=,tag:KoSM39IaBisGN8joSbMNrA==,type:str]
    namespace: ENC[AES256_GCM,data:faLMphl9/AE=,iv:1W7wYHPzNdemViixgn4iHg6dzCGFubFox/1YFWVYB6g=,tag:LBsB2fN9clEF+LldHHDSHA==,type:str]
type: ENC[AES256_GCM,data:kO6zIVBW,iv:1SrJJZ9jfoP5RIOwHkJldFk7IgFgepxYaiKke9fnxM4=,tag:5Mu8ieQC3nODu+UWvpFJEQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:V16tHA5mCq7cDRBYuShG9/snAwfDltdvJNtOwxB0,iv:j8D5ykKtO50JJWPweSFdn26jtu3YMJeHHidtSRuBEXQ=,tag:csJcWT5MakipX/553uNNvg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AZZGIaLohdltMpVjvHFVhncHoaP/PTURp3iD/+UNlCPv74LIw2fXpQeZHCE=,iv:zPV+O+UBSZh3v+bwUiGN3BF51oveHKzPMlD4KKjkNM0=,tag:EB0VWSbLN6zFyEwG2uDp4g==,type:str]
    #ENC[AES256_GCM,data:hlTXt5LFFUni3ZoXWCqs7jsDFrDHQcFaWvn8Vz5i,iv:9zF+iFJunAwklHujYp4IsVjq75lMA6h+7V5vLKlSvSg=,tag:8C3mNybkEUDHP3sdbHZ1qg==,type:comment]
    MINIFLUX_DB_USER: ENC[AES256_GCM,data:9m08XgUXEfk=,iv:H0Zao/CQ7dnX/QNMOhED8hPgJBh34Hlxoxm7eQj/cz0=,tag:wzn9Hp2wfJLT1YnWdj6VMw==,type:str]
    MINIFLUX_DB_PASSWORD: ENC[AES256_GCM,data:IDddhP1RRQqwcQ7c7iZmi3GNUOySTKMMAa4hp2YrY8tMF8ForNaAWoBEVXs=,iv:D4xKmIa/E5UJdxAAwwBxRxvLxUoHDMZN0xVYJlXjPOo=,tag:DFxHJSRaslbT+SfSxL7GNQ==,type:str]
    MINIFLUX_DB_NAME: ENC[AES256_GCM,data:sHaE1Nj2g7A=,iv:Q7zBMeRqNRMoLwGEFfP9ZCupkiNkQ9GCwcJ6iF1x6R8=,tag:qNmAPnUpZ6hGGyFLhviFTA==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQkhjUkkrQkRDNmY1NnBD
            YjZTMkd3WmJycmtSN3BBVVhvYzFXSWVDRUVjCmRjMHBscnJrcWdsZHg1R01sUnNz
            M2tTV2g1eG1aNVVhazFYUitaVkcwZ0kKLS0tIFh0RmJBRFYzaTRXZmhvQ2tmaW5h
            NzRDdTFyK2dOeTVZNzIvWGo1c2txdVUKN8lBE3IsxyDmRBWlNoQOnXuuhIw/V6UJ
            PjXYgXVAKQy7iSzg8+yZZzrxKKpETnTBPtz3PpT5D+LZmWQVqZkmZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNk9nMGcrdkxjVk5kb3Ev
            TUdsZVFGL0JDcGZHZXJLaUtLUW5nMHd1QmpZCjY4OGJNV0ZFWnJCSDg4UkRrVnYv
            NXpDYUtwdFRmTjFsME93UVNiQktWVEUKLS0tIFpmdmFEZkhFQy9WMW5LYTBrZCsz
            ZFFQYXJuV1NOWVZWZkUrMzBDTzlzWmsKFV9uGGAkj9atoXkhLixT08eSNty1+8Rw
            hr3dAuePF3dVvOnMz7jnvN7OwZGu4JQPoc1CmEoj5ebsk2hB66XuYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T20:30:56Z"
    mac: ENC[AES256_GCM,data:NHqLT1BbOen9niEbg9g4nSYUt3d1HTEMAOpNFUu5Zft6PWX+j35vSPkIMBR3Ja6yQ10oECoJkl1wZMwGeFvm5Kl4/Exf21oJLbwOacRFg/4OtOMTRc6nWqNhjYw4BkIvWDRL6vM0u13aj9+GieNEFSCjH+lqlaY+KuCpAqmDHj0=,iv:TqSPsZVq7IYK5vv7ALmFCLceIJ1QBayLwjAc/tGzyzM=,tag:yKh5cJq0PwefbHuotMxBug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
