# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to your NixOS configuration instead of editing this file.
#
# NOTE: This file should be generated on the target machine.
# Copy disko-config.nix content here or generate with:
# nixos-generate-config --root /mnt --dir ./hosts/worker-1

{
  # This file should be replaced with hardware-specific configuration
  # generated on the actual hardware, or use disko for disk management.
}

