apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mediamtx-tls
  namespace: sentio-systems
spec:
  secretName: mediamtx-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - media.syslabs.dev
