apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-controller
  namespace: flux-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-controller
  template:
    metadata:
      labels:
        app: notification-controller
    spec:
      serviceAccountName: notification-controller
      containers:
      - name: manager
        image: ghcr.io/fluxcd/notification-controller:v1.4.0
        args:
        - --watch-all-namespaces=true
        - --log-level=info
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 8080
          name: http-prom
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: notification-controller
  ports:
  - name: http
    port: 80
    targetPort: http