apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/lucawalz/nixos-homelab
  ref:
    branch: main
  secretRef:
    name: homelab-git-credentials
  ignore: |
    # Ignore NixOS configs
    nixos/
