apiVersion: ENC[AES256_GCM,data:WPs=,iv:nbe529I3+90MhQlD6rJX65d+k6ORh3DKUeurdvKMGc0=,tag:gIGTGDMI09tVTs1XSAaq9w==,type:str]
kind: ENC[AES256_GCM,data:IT71RsSo,iv:qpuokz3MTbQ9Ln4ptY+iacirAAYkWdZ2C+VLIn3l5XI=,tag:TKQ5Vn/kC4lXmfQ7+mHqJg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UiDqnDE2xLavhZ/p7HuyfkNzHm1LakA=,iv:vuSFgcfEpELuCh7W0DBN5DkkGbMXo7RwUDDWqulKgIc=,tag:IQEXBR257gVOEl7LcDifSQ==,type:str]
    namespace: ENC[AES256_GCM,data:InFIoHKzZYVQOFw=,iv:bZQy9ucIRfQ8Js3rIRCqBxlofU0w+yNPqO2P7p3XBXQ=,tag:csF1a3sd+RJkHu2Vy6Ikbg==,type:str]
type: ENC[AES256_GCM,data:YgFnuP9s,iv:LBcL9wTH954NUL91oKMRpqs1yGZUF2lv8Sqq1yyrbd4=,tag:zuM8VRPj2ZbnkD56+ZOSig==,type:str]
stringData:
    username: ENC[AES256_GCM,data:1QxQZbWT/k4=,iv:kSAVUKsER3gy3QbqaThr0q6prkc5pgFDSEC0YcGZa50=,tag:kQ6prkPXQjeOX5mw9lqX3w==,type:str]
    password: ENC[AES256_GCM,data:i5zSc6PILwMgIkc0RLFYSWTAvD/J4bVTcCJXhjCyU4ySA9smxBf1dg==,iv:DGS3DFyvrkA2HOciTHag2NuLldmu5vmlMCmN9ydN66I=,tag:etlT0acC1vVW5m2V5h9LlQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdzJmNWxMb01zNmxubnpC
            WGc4MC93Q2p4eFVkbkRmYmRmZTliOFJON0JrCkVHQmlSL1Q1TVVReCtXeHhkbFQv
            UFpxRDdQZHZ5bFBESXhlNEVTZHJ5QnMKLS0tIE1DQS9WMWZsOHVEM0ZuWFpBSnBk
            dElQVFEwajZvdDgxa0ZTMWIzNkdzZWMKPCAJ5ucZmQptWpCR6xvMpycLhp9PEku4
            AqUwjBNCeIcjlqcX24cA2E3WH0cmyH9p6hx+rZhb6F/fweh/bkhXeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUmdSV0lSZUxVV3QzdVdl
            Z3hPRlA3bGYvYnJISjM3Sjc2MEljVHRGS0ZJCnF6T0svazcxR2Z2V2s1bmI5UUF2
            K1IyaUVGTG5VdVNuMUtHUWhBNTNjUmcKLS0tIGtqRlNLVmRmaWRoR2xtVHRaT05M
            K05wZCsvM080NTNsOE5LNHZOYnE2RzQKpaRevf/uEEfKTvmuIVxE8BNwMWWdS9oO
            PBV+hS3ytd8wbfwXkHNEM/xP5GcrRW+eCs+O7KTVPRfH3zIcHkbEyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T14:48:20Z"
    mac: ENC[AES256_GCM,data:GxIKbnxGtUDBEpe5EvL4b0hR8ymuItMDRvIEKAGrxgMJPfHIHVzTA0AH8vmeUNKH0lGuqAZQ9BKxS1LkjyoI5YJ+Wxx7s4UHKbqwq8eq5TArqIJP72FLfc7GwiktaxX0r0ObCeRb4IV0Ptstv3q56KQAFubJ05anK6Cyh25yaDU=,iv:Or1zpi9a3OWlsp6tVyLEohGgnO6xIc4q4i6PywjMx4c=,tag:Xd15T9HxfBYASuuwYLVTzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
