apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentio-mosquitto
  namespace: sentio-prod
  labels:
    app: sentio-mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentio-mosquitto
  template:
    metadata:
      labels:
        app: sentio-mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: mosquitto-data
              mountPath: /mosquitto/data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data
