apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:S47W0MtIVB2qUg3mZW+sHTxjJhzKwe4B6syL4CnXfdiey1Z6xD/ynCknCZYPVbic++gA+M3XS4tdF0lSp4h8QuQkkF6wAgRA7fxRS42nN79ROmMZEydAP3Kkn2cHc2+zQ8UWOBwY1ZB6qDtAHVu0gYI+XGyrjaYNX43T0hLBzPqSUIM9gOevulAcOK4s95rZepvuz9ZziLnpoN62YC3T63gXREC/,iv:Rj3hyswgM/c3+sQp0PUd847r4sN9COXky8KzX5U5dOE=,tag:A+6j4jsilJR3lrBZNwhb+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNVJFcmxtYlNsM0dsSTBi
            RkM3YTA0enRqcVVQRlFwNGp1UGN5bUJyYzBBCjhWWGNiVUxCNWJEdmZqN1lHdE1X
            QjE2Vnh6cFptZjljeGZLdlJRNzVqbmMKLS0tIGhDTG5wNHl4VGE5ajdUQkdkcjVT
            bGFBOENJMUhzSGZpRThkZE93Sm9aRW8K5Evr8QYsYZesJaVGyp6I+Vlbse/7smsD
            1DnAJccY5h4H4q5uUmQZ8/ubR+e4ym+Iuv4xKBpEi1Hvmcufbfg+Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T11:56:20Z"
    mac: ENC[AES256_GCM,data:UB04Exh1oAbCiYfdQ14ajBhntBmoRGtvQvWZ1osbAaXYtXKuRnee93Xk3O1jsADLukYN0FOo7+a/dpzrhY67OVw/yZTevLC9lVPeZ/VngKAa7ba9F1q7L+LuqxwAvbFSebKj1eFcaHo4hMlcV5EwLr3zjYFh9RfzVjt0gdqt8gM=,iv:ctHzvm7mAW9G0hQy70pPYMZpnttHTAvT8J2d6nvm7/k=,tag:9sbhspG7bQhCzBdFQEcjFw==,type:str]
    version: 3.13.1
