apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:N2ef0ke2RWi6VxgF9WWOwuY69Xo8X2v4t+Qvd0QPTGiFi3Q2qcccEIzfOCR8l6qJDbsbvXRdD3tMJi0doh82zR2ej7mp90qO6zROxJbEW68/Edb/vgeR94Gy0NPcIPybtXKMh/ljX9QdoWveKlIzRfM39uguRDd8EIqPwKIDgH+lwpukrepaCG06GlyN/Ru8uaCmyHXz3hLhqS21zvE0D0t1REhHRIYH0yZcCj3EsQadgW6AgAPeiA==,iv:lp4HEsTe96DKKyx5f2hx2/T+TbXNVqohmYgXBtqoC6I=,tag:t0IOu+qVF30yyUBaiZ/PJQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQWxseUEwNzZpSlNmVlk2
            TWRBTVRoQUZsbEhvUWdTbTNCeGc5TmMvS20wCmFiZTQrS2dQazY0REJ4TXpxbWJa
            ckZjY3lPclBtYkVJU0k0L1RQTjlEU0EKLS0tIE5oTDJudmY4K20vVTVpb1ptYkwr
            d09ReXVmTUJnWDBxYTlEOWxhVE5QancK/qxM9f/Pkyef6NJ6eBQasA6TWmoCuCSj
            zJCHgpGiFxyoUec78Ml3tf8tnuXwMymJv2jHH3OF1NBp+4gxlEpfdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T23:38:05Z"
    mac: ENC[AES256_GCM,data:68A1aLsTaLQPJ8GwBuM1lsW2C75/gUPvE5sPn40etVhwFqPGeTyRKXHtQ+YZlrrJRtzI+J11yeqOFNFHNmZbsF/Wj+uzfyY2HIvEIBPLbv+kMkQHeMu76n0jFWJl+e98s3nQ+saYJ3ogu2o4PdLAJ2UETXR1MTpoQaa14TK9+d4=,iv:BDJqsztTv9Su4VNDVBJpwkQ0FoV8dAgXu4Jcne5PZI8=,tag:OSiFdzUu8u4OlnKJLQxjOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
