apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:CxlDw1fvBPL7AMI8QLH6fVZjild7Qm+d2lJtBtWlcLDhCFJcpcw4lg==,iv:cNDP8pkKZv+47A+YYp4vrf5JGDNaeFcEhSB5grpbKWw=,tag:W81vcE8gKs/ca5ut3f9YSQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaEJPcVpwVVo4alRhbi9R
            TFVRSUkwOFlhcVpTMGNhajdnVm5RcXdlQVRJCmM1QnJFQXNESG9MY09xelR1ZzRN
            NHMxSUppUzUvMUVDaEVZeE9oT0Rna00KLS0tIHh2cy84bEtzdEl3bVBVaHU4ck52
            NFJyVG5EMHZvWTl6TkF1TUdNRVZVNWsKK0UDkuM2jU3lXDs/nAWBsR11D1jRk0CJ
            IPyyZHcm7c4noyBscbq7UgntDt8n//38QvSCpjZkUjByxAde6WfuGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T22:57:46Z"
    mac: ENC[AES256_GCM,data:2WHAb8Tn3KK5h216XorxuWpJg36efUUU/NWfaEPzD2kmnbPgIve0NuM4uzS2A66ByquK34tuTwq0H8W0SPeVi+54o4+D6vReKTs/6RdRLfa55vdLa2ix3hhkSjDKmcnKoxwVfmlDizaHcJhDuvks/PQ76vAXq04cP0I8UV+v2hI=,iv:zKa2K59nhNwQZScJR6FYZ5YD8YbH+GAJtshXQjFLp0c=,tag:NfHGzWqoMbnSWIDj5P6c6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
