apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: sentio-systems
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:qAvIIwLBM7jf0mXgGp1j2qZPk+0abrHAwHU+GAx1pCssJc/UZb23OHEsmm9oWGaswC96wWCdX0se+awCZ/Xj4k2jOPJmeF+wLma8VQs0T8Ex5Q1RkL8LgzW3bNEVTsU2Grb7TYTu8Us4/Y41+cFApbDhzLg5l/GlnufiES9VenGO6CCSYANm,iv:nPCwVnkSwc0c5af3dOZXBpRV+dBIgznli614K4YZstE=,tag:Cy+Q/wOl9kYGcER0zB4dtQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MDZkUnpOR05lb1FIQlZK
            cFJjcjRGelZzdjRic3MyVTFucWZYRGRsSVJrCmVTT1B3UEpZV3lRKzdxRWlkSHdR
            SldrT2pjZjUyTGJkb3hrQWd1VGtSY0kKLS0tIGxwaGlWMnZCbWgzTUpiMlpaaGRP
            V2N1cXVxUFZZZEVvK3kwbmsyU3kyODgKSXmTL2KzmWsbsPnNw1fAm9etAwmzP6jA
            6eMYmkmCy1sxLYfPnIA3hFBi2F3a4G3OuvdrZ02+85yXXCtO/JUiNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T20:22:05Z"
    mac: ENC[AES256_GCM,data:ziB2r2ipNovhamsRsl3rPyzmfbEKAP7IqWD1/J9ItNNv3pioxE80iWwJVR+xn3pUf7y4OX8prmD4u558F/MCWVZAHks9H1zRcvF23O/+GbJFGrbqFiB3OZdxlQylTPhzu9BtwY17eUaPy1u7tgkvijJyZUN2hxyb96JmZI+u2gA=,iv:HZwgYEzFQxD88bzZyiFYDKY6QWVlXHA45x/jvVtUA6Y=,tag:/L6XLUToh8aL6qe89IukOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
