apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: sentio-systems
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:TpYY5vljgLObCbot1uB/u6kXSoYgEzhmvU4ZMY4KFSF72Ji8iINbouFI66X3oxEBpIQ56es7JKdugF3dRbkjgUrl9DZPDSoURhQGZ3NOGpmixqm53wQ91xazVywd7Y7MoU/+HyE9xr0neZrHpkAHKb11yRdv71FayaH2IPAR8zzBgHADqY+e,iv:wWe72KZYdVVDVm8q6LnZrTnLFeE2J7qESVsCL1KGgp8=,tag:4IVDAWI378BDO6UOv+3jpw==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MDZkUnpOR05lb1FIQlZK
            cFJjcjRGelZzdjRic3MyVTFucWZYRGRsSVJrCmVTT1B3UEpZV3lRKzdxRWlkSHdR
            SldrT2pjZjUyTGJkb3hrQWd1VGtSY0kKLS0tIGxwaGlWMnZCbWgzTUpiMlpaaGRP
            V2N1cXVxUFZZZEVvK3kwbmsyU3kyODgKSXmTL2KzmWsbsPnNw1fAm9etAwmzP6jA
            6eMYmkmCy1sxLYfPnIA3hFBi2F3a4G3OuvdrZ02+85yXXCtO/JUiNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T08:56:47Z"
    mac: ENC[AES256_GCM,data:BBB8vf3s1/WbPBClWsVEpa7QPbdZG5SMjyR0zE2Eg3BocI91pnVAWYDYLmXeCdc7NBT9xGDXJaDGnq7Qd0WzgC+btv7SQXNeLiHe7h9aEH3LHjTriYTKrscyD9zFeJixJJP+rVRulDa0ouvctBPy5kmXEE3Ts2LXDGSTeen6fFU=,iv:HNuwqTYzHf6+bQU/OE6q8B++wGLnYzPVsxZ3BmiP7mU=,tag:gMphJ2NSd5m4tpdWcX8dcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
