apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: sentio-systems
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:jXHFDEJxzHSYC8fUcMHvNMo2zo6O8UNtexq9eVZnLl2XJwi4INiJ8bhiv0gyJyioC5gdQcieAGGODM0HJ9UTBvni/PF44kQObghCxbck06nGtFOmvGq7ASZbSrNuMRzH+Egs6JVKZYHYb3A0iKxy81NSHaVD+AtgJ0R3SkI/AgTZ7e2kT6CE,iv:Bf1QZrtsHmuPwUgw8AStRpxm8TuSdwz3Hi/+3iQB3SM=,tag:pzdSLw114Zh9oOL/B4ioMQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MDZkUnpOR05lb1FIQlZK
            cFJjcjRGelZzdjRic3MyVTFucWZYRGRsSVJrCmVTT1B3UEpZV3lRKzdxRWlkSHdR
            SldrT2pjZjUyTGJkb3hrQWd1VGtSY0kKLS0tIGxwaGlWMnZCbWgzTUpiMlpaaGRP
            V2N1cXVxUFZZZEVvK3kwbmsyU3kyODgKSXmTL2KzmWsbsPnNw1fAm9etAwmzP6jA
            6eMYmkmCy1sxLYfPnIA3hFBi2F3a4G3OuvdrZ02+85yXXCtO/JUiNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T11:15:34Z"
    mac: ENC[AES256_GCM,data:J0C60/ty1xZxYQdcxirmOVfRVrtPlYlo48eZ8KCRTkkDt/87t6F8gmfNFIDmxGBPhkIalHqBzERtu/MLeSv6jwB8bXaP87JyjvGzM2erqoFUmxgLvY1tvt9kZdKywSxb8xO6c79DOqXjnXcRhVp2uuJrTbg2d6IaHRwqKcqEg00=,iv:YecLA522Dg6pqZrXNQqupA3PkniTvtCOoygx5l3hZUk=,tag:80V7fe9HOUnufc6ABcXmAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
