apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add encrypted secrets here when ready
resources:
  - cloudflare-tunnel-secret.sops.yaml
  - postgres-passwords.sops.yaml
# - grafana-admin.sops.yaml

