apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add encrypted secrets here when ready
# Note: namespaces are managed by cluster-namespaces Kustomization
resources:
  - cloudflare-tunnel-secret.sops.yaml
  - cloudflare-api-token.sops.yaml
  - sentio-systems.sops.yaml
  - ghcr-auth.sops.yaml
  - rancher-secret.sops.yaml
  - longhorn-backup-credentials.sops.yaml
# - grafana-admin.sops.yaml
