apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Add encrypted secrets here
  # - cloudflare-api-token.sops.yaml
  # - postgres-passwords.sops.yaml
  # - grafana-admin.sops.yaml

