apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: llm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:jTilzNGU+WELUOankZxWPvGTbDV+iW1ZYNIC0bLnDDM3m0H79YC0Rk9Qo7oPJcPHTKq3VxM1J20qZYTA0lUDCegOvK7gI6mg1+YMG0GF2SWqOQ3U2VHqjuNw+EiMs5P93ykR5errSJ5ZGVTr/w+j8R/Jhr4vgWZrAQ==,iv:jIvqY2msD4qpqgIfx9FPa8JEPSoxOEjM3ckMN2qlgwA=,tag:87CaGnCxrvF22zaEMmOXKg==,type:str]
    PROXY_MASTER_KEY: ENC[AES256_GCM,data:m5yG94dtLwfBH9zPWPb0RuY14+uJ1xaaFDRL7a6pvjftn4i58GqagBDWtmb6DD8NECff,iv:wjgYNlobn9n4nN77JUSwy3kKGNS9EbuSOy4eDVCjUHk=,tag:XQtzL7OdMn34UTlrWBQB/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTHk0bVoveFFhOVBDeGcz
            Y0tpTlp2OTJqb0NKRkdtNElvTFNUYWx4K1U4ClQxU0QxYjdSUGY5SUUzL3BrU0w5
            bkNXSUxJbnQzYXdSa1NyVlk5QTMzanMKLS0tIDhERUI3V1J3NmgxMVN5ZkdKRm11
            QkxienhienJNYk5ib3pCaTlzamtzSkUKFNjnsB0/TKJwbxBdqMfT4ABkTK2CGUMT
            NI4O4K+ffD2Yg0UGK4m+TkAC5VF4MfUEBapy04MwhS+I092yYBqAww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T16:39:34Z"
    mac: ENC[AES256_GCM,data:fSWwrUi92uMUeZzZXba9hXomlVHaIiwsC3BY1qiiw0dnvHACrLy9EFCCQuy49MRpXx8v7bl2jvlkk+oI0w9Z2p4ID2aDHhiypJI/7altyLnH3TQnra+FLst8GfEyUTzHCS5winR0V7w8LyF5Rwid84TNQ5mzMwwpB5nt04jyB+c=,iv:OFnqvS858lFkwkForLEyqFgpnaXChjqkAn7h073wlU0=,tag:eFXySe/d4J8kJ3UgR8syNw==,type:str]
    version: 3.13.1
