apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-init
    namespace: postgres
type: Opaque
stringData:
    litellm-db-password: ENC[AES256_GCM,data:FRm3nLkuKngn0oHvuCafVeJNFj5OGdB7CZpMYGwIWT5G+7Wr1zxDPw==,iv:nKASLmTrhY4LiWzy1C4QJkuiJwQh75FZeLiFDXElxYk=,tag:PVQjRIpsR3ifravy7iYfjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa0UyWEZueThyeUh4ZUF5
            OGVVSncyOXREdVlqZWM1STdhRURnM0NWRFNrClFSNGltMXJZNXJPVjNTcmFuNjFD
            MGh3by9LQStFemF6amh5eVFtWERZSU0KLS0tIFZPbXpTVnRBOEQ3RVZ2eXl0WkUr
            T25nd2k0ZzFMWllrWUYwTFlvMGhMTjQK5kt8GqyF+9SVHqkxrMvK9P//P54NL0a1
            +ET6PUFhArLDhPrfFlvsHxRm5wmNZ8tIXq9r1fsf8EPL1/F4fMWUnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T16:39:34Z"
    mac: ENC[AES256_GCM,data:Umxv90ZRfXt6GkPwKZv8eD9Q9sbS+fD7i7nPtF1sAXeerAEQgwCIb8DrtQRNQhN404/bLvAL8YRKd4hNs1bBDsCAaVfB5bfdDEKalpvtQSbwrLAZOtRGzw08+2ttPqjr13wtKTrvh2tTEHLiqB0k80ikZWKlKuXkiTOr7cKBTnw=,iv:lgWpBASq5HGCxv1FoE4EjV8BNms8mZttxU8utwc7Q20=,tag:1B9K7fgwwnis6Mb0yck6Xg==,type:str]
    version: 3.13.1
