apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:H+t/tJfTtQRt1fnKBGsSoqDeX4Q=,iv:66JaNzf2STALzfclAZI4eaR6OTwWvj+yiSwIo7fUt5U=,tag:laIrV75EnqR390fSsdOFTA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8enExyr1rKGhPybk09pRrUJehfyS0L0+XOtuttUKpOt3XJn8X0qlPg==,iv:8PeJHdn8Beilo+lgPBw0i5G594nNW7PJNiDM3BITnVs=,tag:PECIl9ZVb6mGacsgdF9Jbg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:7zbTJ29l2Ng676sm+PJtrECftapJxinBkZs0c+lK7XIZfMc=,iv:s8LM2Vqn6mYt0O5igJQIreeHR6i53oKrN9Mm2JZGueg=,tag:BU3eyRMtXw88Cdtcj+lj9Q==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYnY3QlB3UkRBVDZsSW0w
            NlcyU2VONzMrTHpXa2tleURjSXZmcTNBQUZnCjhhRXFBSGYvZyswZXVDVXRLbXFq
            WVR3VDR3N1lvZEtyV2VCNEFzR2I1aTAKLS0tIEVsUXNNa1ByM2hOdXRVM2oxbEpn
            Q001S2YyVmd1dDVEY0hzMGwwRTRENnMKWm+Mfv+DIq1a/4Fc8H80IQILPoqVGoF7
            VgDii1DuXJpBic4/QPH/yvC911tJ67nN3BNCfurijAgWuQejVqF1Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:40:44Z"
    mac: ENC[AES256_GCM,data:cBldpSfvoskDaY7NhRnFN+Wh/HF4wn2zuH8LHrFh61yXvGGaFIqZ0n4duTKVhKFX73SZJ/o/AHNonEwjumtSxuv6QmSrugc8YF1eNgE/5rkmjTWk2LzLprxlsh3lF7qTCcqrPuTXYQ8CtAQPm1VaqMP4S/SSiZAx1UhqSnJG72o=,iv:jApbpdgbnm7Fktza/c58dQ9b2YsoHi8Ri3DlPmLLt+A=,tag:OpFb77ulkP4Ix/KXgyjA1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2