apiVersion: v1
kind: Secret
metadata:
    name: netbird-helm-values
    namespace: netbird
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Mj3Utt3LT4Nk6sCz4ietyljIaCVkdYv47Q34PuKinDmXmXadleP/pociM7gj5winx638u/aAXkeMlDIxuCOIBqJ8DOSnfpdgDpwgP0vMQr+6USA=,iv:iYsKfYVlvd8EKxHgIW1BuXSF5BrmHysxWaMtnszIq/g=,tag:CJ19axswA+VeHGVB31Hifw==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZlY0VWxxSGcxYitIcFFV
            KzFXRWJYRWFGMUFEUlROMUtHaGtuOEg0OHdnCjhPVVZKdDlNSHg5WHFKTmFCNHZa
            bTcvcGtWakdnbjB0dTZvcUtSM292QVkKLS0tIFRYZEtsNXQ1WW95bTFON3l4WlVp
            QzJPTndJemRuSGZ5UFVNZSt2Mk8xRXcK/B2snoq7K0u6/DPL4kylFVtGQ9Q3ALPu
            c0SpKuQ0OpE+xwD1QFfLKKVaN/quYBCHIHE2h2m+kJiJ0OXBvIfZxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T19:05:28Z"
    mac: ENC[AES256_GCM,data:oEJj2T2MB8v7CRNOM7/nPy3RLecCXgl5zGgAfCt1fdzRo9M9nw5/1EaizjenYNi2gZTQAJAVdqJARgxMYgDV4YWdw0ePOH2LAHNG37CKCdQo9HcnRjyJssO/6fnF/KjDSdtH90+l+ofRBTmXWpd6hOCFyNq1RL8nv9OEn4OA99c=,iv:IXDO1ezJ+T3LWvpxLU/IUlMHoi299jXb2b7RrtomLgI=,tag:Lx4o0fAoW8QaU4UWX1yFaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
