apiVersion: v1
kind: Secret
metadata:
    name: netbird-helm-values
    namespace: netbird
type: Opaque
stringData:
    encryptionKey: ENC[AES256_GCM,data:GHM8Hxt5hptiRmKqjcqRAydtIFtAvxt6h9SAL3eDL8no1xnOOB3R5X23tm0=,iv:zOzWv8hQOBvtFC1XWNZnlEmr9txC6l3EDDBusRkrF8E=,tag:C1wGOQvRYqr+F1dN8MiQnQ==,type:str]
    authSecret: ENC[AES256_GCM,data:eGCJt1ZKM/JjZdNC/NL+yKyUPHUZcPZHnbhJVDUhePLJ13w8l+O466fcGQ==,iv:ym3Poo5AWfFpH8dJMZgdQCGN0ujO+J092bkKmkZoheU=,tag:bvDSKvdEAEM7ygr1HNVHyA==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMVdLaXBOZWdleHZtRVRG
            M1RXbkN4eGxuTDhzdVd6Y2c0aU5QdHN1OEE0ClE5WnJkaEdvdXZSdlB1VnBhdmFW
            WSt4YVhwRkpXVEUxTlBPQ0NBMXJ0QWsKLS0tIGYvQTZQYS9XS2RxRkJhblhhNWx0
            RWFzWG4ya29oVERtaTY2elZmZkRFd3cKWzXkKbkEAAmSrkyKyT5Eey5IE5G98PFG
            d9YR/GNGNLI8wFz7RA728GSmElkbxVWNPLeMG4tfa+MlfAZ4GYW1Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T20:05:07Z"
    mac: ENC[AES256_GCM,data:X6rxPmbiht35t7N0Qd6HOczpHwtAJrkuDe7Vum07I2AhDXjSAWCdniL4soVImMrjr7nUo19MzDdbtO/ptJfei5lPfb1G5NptPomtbfV7iSpp505JGuco1KD0dHUQF1S2xBMHe9sCH8oBtR44yyeL9BTSnTpqqNsCAuzc/5xatKQ=,iv:ZPrYEe3QYmzvwc6PsBTuoAyL7gND3FcUyr1SRs+8/EY=,tag:IYR2e3YrHGkPhvuJFOYwuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
