apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-admin-secret
    namespace: postgres
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:yv1RQdOGVzzNoKapAGpKuEg=,iv:igY3qBG+tTWpSy37uqzf6qfcMOCqdXHcAR3ilSbKCt0=,tag:RD/VhcgrNdmWcaQP/aJWlg==,type:str]
    password: ENC[AES256_GCM,data:fQlVP6hGWi3IptiaJQP9LXs+DdBhZrgUH8LxJ3HNmvY=,iv:HIiACtyHB3Mo7jJyyez5vrTOlOmAe/HyK4dWJ71qqCk=,tag:8FKqRK/PKKxMqGe78xg1Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUmlsRnBpYW9oSEd3U1VP
            SEkvWHRvbUN6WjNRQXk5aktRWjhQdGkvb0RBClgxNXpMbnJ0SmdQV2lyN3p6Vm9L
            MXFNaXQ5MlNRWmZNV2Qvc2thRVQrTjQKLS0tIEI4OGtHRUhiNzJRcmVvTEtoNklp
            cmRqWGVBUzZWTVFHQklMNzBERzc5R0kKkc22YjsvlF/TEKCY903bOQpYfc6CDNRE
            nc7HrA4k/s7VGKxXsml0+7j0byFytB4er/P3DcUo4DPZSJv/++b0KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T16:52:14Z"
    mac: ENC[AES256_GCM,data:NPcLD5sAv6GgUf166Vksijrbt950LlWJBYMyk9LVD3q8FJitAVrxdzfWSZYq6qcOmIQWmoIXBzhfyfgc+aExymh5D8WJWTDMrxTwyocyUFsKOUlzqCaue96f7k8HANgzLvxFhzCaMh3ra5QfcrynNzTA1ivHyRzAxHZvQTYgrEA=,iv:qBi5+Amt6diXBNkLTrvzkmTyfLqG9hJgOsaNVwAfINA=,tag:GDE7B2Ci+qMmNirj0X0z8g==,type:str]
    version: 3.13.1
