apiVersion: v1
kind: Secret
metadata:
    name: postgres-passwords
    namespace: postgres
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:7oEwAvbhV/eackX5NqAZwTuDrk2A8TCa7cDg+R8NqRG5twqUsN1pRO9AWdI=,iv:xfXR0/uA6OfJ/bANSRJvpMpS2I2PpNPefWgGtYG6k6E=,tag:5JjMMV0js303J5oxltgk3w==,type:str]
    replication-password: ENC[AES256_GCM,data:n8/j5bjlWJVae1I32c8yrKsoLS2KqFlyUQ2bB1ukMCHcw4qG70b8sTKbjbI=,iv:xb2NBzqB+cJwF3j+rtKHA1a9MuVyXuhj2dCQQb41bqY=,tag:qjNbNlgSqqEDdOOaJ5DPPg==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYVdDMWFma0ZpK2lRNE9K
            MFMxWTlNdXlPYVN6L0tBRjY5c2RXekg0cVV3CkhkS0Y0Zk9zY1NyRm1BVTdSVGs0
            NTVaemJzSlIrWVhEbXNoOGNrb2xaMjgKLS0tIGliS3QxODlnWGRTY1RKalVha1c5
            eHZXNnBPc0FpK2VmTERjd3ZpMnFNQWsKBiFwi648KU49VOKW7BTneJht5VNiBKys
            5In64GUbn+rMQsrFHfsV6Mge5ifobx3tZJwK1gH74EtVbR2OOAuUYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T11:55:14Z"
    mac: ENC[AES256_GCM,data:cVuS9hcWflWSon+nUQZumhRK+fTYCyAAnvQ80LJ2ynMLQDESjdYKIUI/5rNep+W2MXMZev2+a2olXh1CVZ6t32UznQRUuNJ604ltGOxKpfL1etdYbigdZnpvX/umUTT9hj7Ub22l2niXzCz1aq0mKDmqTfAmwkT6kX5wEWfn+bM=,iv:bbc1lo3cHm7m9AdYeZTsQOQD40Izr3W8FRF+TDmZAgQ=,tag:xJDmzT7Tmo4U2BFeVNgsXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
