apiVersion: v1
kind: Secret
metadata:
    name: rancher-admin-secret
    namespace: rancher
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:svxc4k8XhefCfiR79w==,iv:66/8qfxVkOYTz9IRIP7C1AwyF7y4FPSIq7MXhv3pinM=,tag:0+Lo6UAclCVC0yOdG/6WMA==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkZmZ2w4NkdFWFRGOGJE
            eFBlSzI4cXBEa2dvSFRxYnJsTVRFTkFqeFdJCno4VTQ3R2tQaDJ4KzJwMytxS3ov
            a3VVWlhzSHM5THI5cFBFb2ZJbVh2WjQKLS0tIDc0aFhVQUJKUUN1cU9aUG1FN21K
            aU5JVGVTci9WQ1ljNlJ3eVMyUEZxeFkKhDQtHgOO1kTynogr74DLlpO5edNKbrzT
            SiUciGfGUzuJ/UaZxuMiznHatjl0LnOn8oE385rSWqO0o3Cievt/5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T19:14:19Z"
    mac: ENC[AES256_GCM,data:uYxKILeATZrN6NEJ2rT8PLN7R0AAN/aRoymkQ9QoisNofqp14ltvyCDSWily7TsF4O+nbIpHouSnMJg6xFFX3zlB417+r9kAUDxDSEWD1T5Pm+RIy1p3GicdvJoyh9nR1DGu8b7I5ddXvQ7Hp8kYaFRT9dXoJ9OLdQOh0QmHbck=,iv:7ouCPAc0wAHiHGX8qHfr8FiDMUsfjzkJdrBxJOX0hXw=,tag:4ZCxbTVKAPf+azknTpb9Yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
