apiVersion: v1
kind: Secret
metadata:
    name: sentio-secrets
    namespace: sentio-systems
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KeAYHG2Sxj5J+iSGVEnG9H6dmd6MQ2BjsSRXMzKf6CIIUTx8kte+ok/BDtKmAA+M,iv:0OV4Q+FkY56+b1utC3nkjscAVyWgf9ljZGmcINUPZls=,tag:ZRrP1tCX/8yn1yJkgu417Q==,type:comment]
    #ENC[AES256_GCM,data:Wc3mcEWgdlcZKQAolk39SbtApvmG4ckCQ/225uEpXYt9kjLHr+OYtXYMGH5cp+YESX8terULYf3legW2ZEuXZumSn4Zj+Mhc+vw5H3xT5OA=,iv:BMkndUYo4TKd6mR3zNQk9oFPdTA2MsRbiSFDnlZ7bmA=,tag:a0lEANnQJ6uK0GCFMyMwlA==,type:comment]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:z9TpGc2aKd3nwwSrejDJe1nIeV7cSNrwAasVGaC0llU=,iv:zqpNz+KyhHKQ2pfr0/PQsz1PEQei6U76Dkikxmmy4BE=,tag:+tJVzMe37BY+bgY6eizooQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:Uht1QUoNvgzuLCK7uzChUl2dO352yGuvUo7npT7N3Oo=,iv:w18LUQVoGKTbjpZG+sxT6kHXsFqAsFmrz+wgU8GYL78=,tag:AQh/8oqDOHAwMxeJQ4Rn4g==,type:str]
    #ENC[AES256_GCM,data:pkyCJzudpvFDuBUc+rIH1gRs1dXbcHAGfcpxWP0=,iv:WnXRs27DcULBIQ0CtUnCGbiDEbSBj0sIeLEUJaIwxj8=,tag:CE+oZrBTDMHuXxxskV6PsQ==,type:comment]
    #ENC[AES256_GCM,data:dJobYlEcGfVe5FuBXplY7b9BUSZsHPL7b9MvZMXiIU+5LYbJHMCBtLTGST2+LTUmcAZD636efYyLeMEtwkbd0fspB0pewQ==,iv:kFF3TeZu/28bzbUn5VFSwZ2dHF9i8H+m62+zh3g/KHo=,tag:Z00daxp5DkKIFhEitxbRBg==,type:comment]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:gOzDphDaIYDXubzpp79yI03VJBwV0XQypE34fRa+7yE=,iv:NZrurnQITR4yslTxkFXSX+t9qu+Byo8O7WEHGu2H9rc=,tag:yZvfrOHjbnyREVpoNDroFQ==,type:str]
    #ENC[AES256_GCM,data:ZJTDEFxM3tLgoDG93cKxOIXu0paWH9PVg6vYEcg=,iv:qH1SRYlLsN5CqjPWsH/c+GuEz4baZCSr2+54uP/qlCY=,tag:dR9xzshM4HDkbX7XlOx1fQ==,type:comment]
    #ENC[AES256_GCM,data:qCbMxPVcvcA7OQb3HtTu29KFGvk+1F8IZLBcyFH9dnecmPmKv+ysmZAwnuLKO39ylkYlf08ZrmNvzQ==,iv:X8fNnnFImnThMuC7BGpxHjUxIdzIb9t/bB3I5KdALvs=,tag:61LZnk6NW+SvP3ws2q8Kqw==,type:comment]
    #ENC[AES256_GCM,data:tv8oW9xw2pY0m1Uh/yykxFxk0VgnrxX+6PgeTKPNIpHBMIPy+g5qSA2taHTKXusDuBSen7KuipZVul0Mptwdu3id,iv:hVAchkbZcmUwPz7Auvtd1Mzchx8OWazofIljXo91eZs=,tag:p13NcuoViWAgPd8JZRwq1g==,type:comment]
    KEYCLOAK_ADMIN_CLIENT_SECRET: ENC[AES256_GCM,data:LHqAg0dUrDx8MSaqpwj9F6khmrQ1wY91P/KVgbnH5Lo=,iv:yKWy7YjG8XbJfXXqUoSyC4stIE6ivqatLyGDctrrEhw=,tag:Xyg5G+SVod//QIlUCQFTPQ==,type:str]
    #ENC[AES256_GCM,data:0XNiKoT7UanA5GbIOqpNSAAg5l8fOwj2dIEEhzc=,iv:8pmJlsnYL7hCfCfb0fSC7kVbLcU5AbKsCyVY9l1bFeA=,tag:VJSqrrGT4vxf7GLBNnzl5w==,type:comment]
    #ENC[AES256_GCM,data:f54rWokKrqYi7PBOL5ToEhDZEhUwy8UhPstZPiOYnnRdfQ==,iv:kuFhLqmMrB64NZSMnbArmHes36P5qoD/eBnh2K9lFjA=,tag:Kcs+s24vUjpIjZ0ed8Etvg==,type:comment]
    RESEND_API_KEY: ENC[AES256_GCM,data:wzu5E54NIrL9RJ1wEYXARQNqS/kDyE4RWfQQBNdurpaxjg6L,iv:kE6uMnfM3LlWGiRYhsXK9IWbXSgRN6rlt5b+aPFRnr8=,tag:TteVuIl9Zy3evQl5Aj+1vw==,type:str]
    #ENC[AES256_GCM,data:WTilO3H57DmwR/Cie8o4lOwe/7sK2qrIDqmNX15xLHjBt8IJ0wCp1bLnepw=,iv:6YSUAsO7n3nnUxFyOJTz5+TfFTbCArY0KxrmE1Rjrms=,tag:aHjXFcZJA9R4BNynde0L0A==,type:comment]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY20zclZtaWJmQ1dpK2ds
            Vk1pSUljbm93M3I2dEtZRjI4blAxUUFxbXlJCkNEd3ExcUtSMlh0RndtZEowL3M5
            ejJFVGhFbVVLQndRdFhZWWRXYTBFQjQKLS0tICs1L05CdmNpaHZJZWkvSjEwcXNz
            bm1nT3ZXS3dEb3pOSTBlQXVuM1JXQ28KupeNeW6L3S3P1LDJo2jQF+A4gKlEeaB7
            ZCQRTms6AJjTNIGr50J3T77HKVMrkfbT7xdXtiYo2XiHPZhwb6dGKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T00:52:35Z"
    mac: ENC[AES256_GCM,data:okh5+o4QJN2h+f7qT96HDUGQXV6Wlby5+2i/eM68SjFyxJBTsEmhpQBVYbUS69PbHsxIYKXHlHN0Nt5kbCQGjbUEUdFm1Mzvpr1VleyM4Y74i5hD4xaYPp5zrguXtNzoXlH1bYytUpOdozV68kPhjDBCY2L7GW2SRsr1sNM8OS0=,iv:WdHhO00xpy904Aus4YVFX1H7oRlwUSidKpHCaZCPDbo=,tag:/bHlJm89UcpyAu6x7FHTzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
