apiVersion: v1
kind: Secret
metadata:
    name: sentio-secrets
    namespace: sentio-systems
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XPSrNBpfdRK2WYfazKiAk0842qdA/kdoYAIXT1DLljoy4aghDzE+koIBlIliQ0ZF,iv:gyN9/bF4K2M4xeemcgfAcUtg6WEM1u/PbImstnUKgmk=,tag:GIFEQ9acD9/HWj2zpx0i+w==,type:comment]
    #ENC[AES256_GCM,data:2JCaoLQci4rW34Zuj2I6p/qKjZlNLPCuNq6TJ1Fl/1Y0yWgmWa8vzKC2odCo44X1iGQELjEfNF6X7j/DKRgv4A9ULWeCFR3/Dm4bk6nxsgQ=,iv:366rIEMDQEy1w33ba0Lyije6acGBHms1w/mTLxQVddk=,tag:fpMQuG1lW9U8txPNzY/ldA==,type:comment]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:iIGqBKreO1BdE+fFvuCmV+fwashvFQTst4+LEbIwtQw=,iv:l3TX9DZaJoIZLhU4BTFlMHloEAA9HfTQT63n6S9KzG0=,tag:nF0nAWJOEbS+4iksq2deXQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:4ZT75vsqVSY2/I3P2IgsMs2J6qLFdR+NHLXCC9JsErE=,iv:s1oZl8HXEWdvH20DPNrK20FO4iAwfTeOKkLkr/L9sfY=,tag:f8xek2wNxCb4zET8dDW9yw==,type:str]
    #ENC[AES256_GCM,data:cITFFgYAawaBQXupZeO1li3FxBS8KfaL/HNlhUQ=,iv:MnwMXkgjoA9K57W+Djmlz88hUtam+0hvzHcbAzI7bsk=,tag:5GE0HG8A1DZ0l798HPXH3A==,type:comment]
    #ENC[AES256_GCM,data:mjKqbLy6+UokOHfw52HjCy9luLF3fMqORQCerZt2oAMODP4tQ2CciznnUW9nLu/Y4cnxFydsn9jk9z2RZhMAWuqUg0PLBA==,iv:MB7jcVCA65KVUsNfWvRwp/M1VyKhoy5KUbdGuAQuHjk=,tag:hE8lrC+axEM3hIFboewHsQ==,type:comment]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:VxlyBpZimge4F0nB4Va93Sm/HoUx2XyxRc0ooSON8Ws=,iv:YElEhGb/BJdtUWUm6ucQqyvyVIPl6kFlK+Ax+/p32KA=,tag:pMtg5rqfatNtZj0WRgqk3Q==,type:str]
    #ENC[AES256_GCM,data:AvgtsQtT7FRThDNg2mfLYwqY1TxXvK7rfTXkwWA=,iv:oNNoYrlrxaWfv2S/ftXe/plAHhZB2LnTE+Kw2Vtchek=,tag:BGt0joUntTSzo36sTZUh/g==,type:comment]
    #ENC[AES256_GCM,data:oxGl7bXOrvAwsPtiOzS07bN2zd5Nsfh2GdjVrKwkRnV2Pssudzc4ZOX9VVPvCw0CsIlPlurvoARlXw==,iv:kukmT7MNJzqlnQ54rxGRcI+G/TmOS6Yt9N+ZHBk0rUw=,tag:UqMWy6CQ7ePOUq7d0yvKDQ==,type:comment]
    #ENC[AES256_GCM,data:ngZH9e46dnUYJKbNM8V9SqtW7yFDHM3MR8LioKqk4mPsKiCWiq3cpnTiEiZt99rsEG68PLPEbYPnbxVI8rcQk4jw,iv:HhE9yYVTPu1EZQXJmAUxM7SaGK74tLI4tv45IDFdl00=,tag:M9+LQU9506iZHwYq6ef1Nw==,type:comment]
    KEYCLOAK_ADMIN_CLIENT_SECRET: ENC[AES256_GCM,data:3Q1D+OXn4NKXHcc3YsMEF/krqrRDl9Q+VxUguBnvUDw=,iv:6CD5il9BZPdb8b1WzYSpH+BqER1l3ttWfTNnwhJfDkE=,tag:0cQH98J0d8NEvx1vu/XQcA==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdzVnY2Nnd25Mdm5keEJI
            K053NmptQ05IMjNFTG9sSkdkeVdxK3dTL1VrCmJRTmd4c0prcWFzRHgrZ1BiQ1VM
            b3pMVlZWUld6MFdVenRlT1c3VDczYmsKLS0tIDgwdU04WE5WdksybWpmekRYOGZr
            RlNzdnFZTmxiNXJaNWYxN0JheWdDSUkK2wmKkZXfAxJ00a+gXLHq59+dZq9YEYOI
            i0MougneoCEf0pCAmZT7m0r5cqUDIPsTp7QJdxvyPvcsx9UokVIbDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T00:58:39Z"
    mac: ENC[AES256_GCM,data:c28sZSDxd3VnzFaCICBAePe3j4PwUbQzdorpZkuic3Cdaqv1eT99CGwYfywadDUuz/9iDNiXqDp/5VtSxszMlCQi+j47oU/JBDoOx9SOmheQEOrGlU4VOMbuMnoS6ICU+NZ1G/ph7+HCkqFlo35hmj+c23B03JMWGhUweuU0VMM=,iv:a7BfjD5xAArOmfz5IqOZ+4/N0Vv5Q9xVEGQgdvwDRCU=,tag:thVFE/Z4sjR3VTV1/0Hvqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
