apiVersion: v1
kind: Secret
metadata:
    name: sentio-secrets
    namespace: sentio-prod
type: Opaque
stringData:
    #ENC[AES256_GCM,data:sDhHq7KSmc7U,iv:1i7lXkYKNkAJnFVUlgpoNIoXXpCjNlIaQngfO5Dns2w=,tag:8hkHE1pIYGE8eAiw7+Up/w==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:g6AH/kxZ,iv:G/04ODhDrLaZEgYXCTKBdArht+PkmY3xc+V0Q7Er+nA=,tag:gHKX9PTH5WcnZx9nY/W6ww==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Zc2QJih627Bmyq8=,iv:/Gev8Q/XOiLX0DgmRD1yXMTvV+kAbr8MtMzb37OKkzE=,tag:y9GWs721u0+jQfJ1HTCcrA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yQgNL1/y4Qv2Lgn7pLD2tT0ioGE0/S3Woso/BJ87egI=,iv:gcnITs8ibWJLOezfgR4zZvJHvlvfa9MSeRKXmQEITVQ=,tag:yYuNOs4WO20hLFPcjtAbLg==,type:str]
    #ENC[AES256_GCM,data:tTI/Q4CksE8V,iv:fwgD57Zo+AJJ1azofjTJi0AHdQ3knmNRCsClo8eCsKo=,tag:YBF/w3rBVhDYwnVjYIcW1g==,type:comment]
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:JHPFHqk=,iv:I79t+KzPSCPL4bha8rdeeZx0ghz9V31YVZ0A+YoBeow=,tag:sB1vVD5Vgcj3LDrvVOa7Vg==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:abJp/Va0VDjoVycBbTByq6eCq074dg7PDM3H8/sQ0x0=,iv:8SZmHhurpS+rJTgU3Al6ZUi1uZFjEQg9rCOx2mzajsw=,tag:AVpqFxevFzF8mpqXjyBDNg==,type:str]
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:a4wdtR/+VEwhD6R0oWrSKUoXR3bqVOTtAhSyE7OX628=,iv:71d5xWBuBj4LjKZivXy3bYBAOa5VBXupjSEWxsb/QF4=,tag:7q+XYTWsGBJ1uhfnaraJJw==,type:str]
    #ENC[AES256_GCM,data:nm+lK4bwqKg=,iv:tPuYdTSrPxb5w1NX6Zcvu0txjd0tgDurffo0KtD4k+8=,tag:vi+ShwN/d+H1RF7v/f2AOw==,type:comment]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:PF56B6J7PRPHkYiWty9K/eBVIme7EtstJyqI5k9+prE=,iv:Hxf0p67FoU65T2jhx2Qen7uShCAxz4LBsdu+/FffDMs=,tag:5lWxDauHwaghmnlJnYWSTg==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:YgnZTr2UKKe/zqNyqoTUl4q933akRwd71bNne8X9f44=,iv:qFs43yWUWoAX924N/CZ3em09UJPhKlQmAm+ZFQlUhYs=,tag:H/bvouconMBfdwrNRHBNSQ==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:ShjHc3Iqxx6/L6CObHX8BhFoydYuJnyxZFHcR/Gy98o=,iv:4ki0LcQDs1QoZvir8oZmxL7yNvzfBVx6ubvxuAnfaYw=,tag:Rlg9OF+apPStICbCm3XSkA==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOVBGdEY0OCtuSTVlbVNn
            VVFRM3YxZ1RNWjVJdWxwQWg4MzAwSmE0RVVJClhGdnN2V0dKRHZqMlZYTWhpZ1Z1
            aUpNK3gzRWVPZGU0cmtFMVFmNjZnTjgKLS0tIEdWQnV0cS82dmZ0azBSTHMrNkt1
            dkZLZmxPcGhxSkU2MmpRSHFtN1g2aFUKzodGJOBMIpcZCCMUN7mg4oOI5oJxFI3y
            i+UngXuzEnPbUwVwuZalNtrWJsy34tLg71iASQhqy/1Bg40l30QkFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T21:42:36Z"
    mac: ENC[AES256_GCM,data:Ij8b4kPnAT2MTfVhY5QFSFcWjmafHy8EbE9e8GixgOcl/M+RoBOrZxn2cxz/ICWIPxSNeA1Dd7r7sseIlEcuQH9hf7Kmb4fGLWe8gAJFQ36MWhd+cjoJPLVEy1K8XdpHdXElDLJbVny9Q/r4TIukDT1A1kMQHZNkOsIySxGg2/c=,iv:iVj+sQk1Stso0vTBp/e04N+tb4NpJGj9JNe0dUbybCM=,tag:AGNLJo0DqFXWaop3VCpb/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: sentio-prod
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:IjuDhuwcTma3tPQNkHhLVCUDlq3OdgZhGfMRUwSa5Fub++ts1Uyj6EuLPycwHuqRUFXLfwWu9UotEB6iwc7r7bejSGVmeAKfeXDHTpQPH66eKw3DWdmXwY7kAjZwGHRVS1lRXggSNBFaIZN43FGosSfI3iRietDUR1M8smQzxLBQTvsQ+dwMxApIJbe3Yg8eQ1vKN0NEXS8ZDdC85oe2q4rmjZfDcvkk6Eg3HoiDA/WBdxFiKUV8LjJyof/1tBHvRNEE4yxIUz4lYUlDT3mdIeFxJAvCKLpLFXxxiNz4smhqZHsG7xj6Qlhhyj8=,iv:QPlv26Q3JciZqQuOlCkthaGQP8oywzLZTYoEuTa6JKc=,tag:otjwSnfQ6DvsHupNkn38vg==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOVBGdEY0OCtuSTVlbVNn
            VVFRM3YxZ1RNWjVJdWxwQWg4MzAwSmE0RVVJClhGdnN2V0dKRHZqMlZYTWhpZ1Z1
            aUpNK3gzRWVPZGU0cmtFMVFmNjZnTjgKLS0tIEdWQnV0cS82dmZ0azBSTHMrNkt1
            dkZLZmxPcGhxSkU2MmpRSHFtN1g2aFUKzodGJOBMIpcZCCMUN7mg4oOI5oJxFI3y
            i+UngXuzEnPbUwVwuZalNtrWJsy34tLg71iASQhqy/1Bg40l30QkFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T21:42:36Z"
    mac: ENC[AES256_GCM,data:Ij8b4kPnAT2MTfVhY5QFSFcWjmafHy8EbE9e8GixgOcl/M+RoBOrZxn2cxz/ICWIPxSNeA1Dd7r7sseIlEcuQH9hf7Kmb4fGLWe8gAJFQ36MWhd+cjoJPLVEy1K8XdpHdXElDLJbVny9Q/r4TIukDT1A1kMQHZNkOsIySxGg2/c=,iv:iVj+sQk1Stso0vTBp/e04N+tb4NpJGj9JNe0dUbybCM=,tag:AGNLJo0DqFXWaop3VCpb/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
