apiVersion: v1
kind: Secret
metadata:
    name: sentio-secrets
    namespace: sentio-staging
type: Opaque
stringData:
    #ENC[AES256_GCM,data:EiJlLB+MaNSy,iv:FW2MEPW4LNFum5hzVuiXjbO81ReeLRqyqlPkhebJjDk=,tag:dEZdnELy0zJggOb1JVzdhA==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:9P+ocGsv,iv:RRspE60ASed5nP88ob34IvYu1ZjTcF9NnefhXHpNnRo=,tag:zJn+9/7734QSfwbwYOZuyA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:povOU0gL0dTd3dU=,iv:FgQzWQLUoyOdWshAlwaZ4yMIVV35mTH3xwcv0HB0lvc=,tag:G11IqmJa2BWk6ptKl9CSiA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qOjtCV4zOdFM0tIYvGbg6O8cH0w7ziqK8w5o9SjByYU=,iv:oC8Bl7sckpXoNo3PG0qQm2bdBmIaWWXEhDGPYScLmis=,tag:6qBw05w64VxPVXz3Ov1kTw==,type:str]
    #ENC[AES256_GCM,data:yAIM1iubrXJx,iv:ZqkvgG4T86wTO8VeXyx9FWW4TbbHJFJSKY9lIoBNmxo=,tag:zE5yU//g3zkL6zMNFd6ZLw==,type:comment]
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:ohRVc5U=,iv:sLf78abQkUnyvdWfN91HqJa6NpLr1BnsfHIsrea1r2k=,tag:48+E0/ay1nYCK8d/V7gLbA==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:mdJ62OGYxaFkCnq3yZEjq3tAMM1aK0qjgYuRcww3oN8=,iv:S0BGfsxUYAy3/sxXNrcwE7srngxmATj9DVX0rutrnKg=,tag:ja0+TRBeuNua9BVh++Tmfg==,type:str]
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:Cegc1j/2HpwJ2ePFDbBvXiYWbx8Z5vC28SP2qeXPBd4=,iv:L0MI1HwDd10StdWuGUtb/tNWuhVy3tPIJfwXJrvBU/w=,tag:EYgSHUCBr0HgndnJefd4Cg==,type:str]
    #ENC[AES256_GCM,data:xxbMLypii20=,iv:3JIPtCviQV3IlAiftZhHbdGCnPqWZ+7dtYT3De9D5cs=,tag:xaokrB8c2QpOztNgc7V+8g==,type:comment]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:8IZ1+KBMadIALCbfLpegnNkpZS0seN/y2/t1JmbXr5w=,iv:gHJfQbAAGCArtaBBclrxMxPxD5sILfIqkhzdNdniglI=,tag:I+lupksJMF5fcc5GDeqbPw==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:sv/Ye8bEqMS/OtdyBji/9phb4aShjPzYvxs486Z5dYQ=,iv:w6t1S1npxBE9lzKJsEgq+YWd4Sa1+EUrAwlrsV4tqFU=,tag:SzMVcQPj7z0YWziDSiOrMQ==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:jHU/u7bQ63yI+O/OA/ORJlw+AZwNTpB49kTFIUHAVRc=,iv:FDbzON0yaOtTzLohz5okG7XwmAW9OdMWcmZIMuWyuME=,tag:sBh9J/Y9K5qe9pHPTdVKsw==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT2R4OWordERTVW5pdUdh
            OWVHelZqT0Y2Z2hjV2dXRjdKTFRqd0hHdVcwCkErVEhIaGRHc0FOdlRLNUZmUW05
            enNLUFdqYTVUMW5WSTQ5TnVwcFB5Y2sKLS0tIFBoc05MTEJuaVRxdXJqcXdva0pY
            d1RkUzkyNU5uNkZtNG1GbEJKYlhSeXcKmKS6s8nT4TcYZo4tcg2iZolU1cHBJzby
            OdVD+dhE+PgjlqL2ryU8YkuqgFpkqb8G2fFf5v7jUcr4Oq7ESbllig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T21:42:31Z"
    mac: ENC[AES256_GCM,data:VIandGyh1IYfq9dC3S2RnzGHTUG8S+yrA108fDcBTnzy5sYeVYnxIOUVgWZOMO2wYIvZZIifIjV6MpoXF1JQVEkH+l6ZrNb9IoyYEm7j97cuXyGZLsyfwH7y9aZjB7hH8M32PI5pC9k1nUEI8fIrgJJVcQsOdnd7GkXfZhAVg6E=,iv:Vty5UVxjBKa1aOA0ElTJ3a7kZojWWHT+DniRPZdM9/Y=,tag:NMmIV5vaKHGUjnxwPo+/MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: sentio-staging
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5/PRSRHSN2yrVTUG+5UXiwq6z9In6TIFkPJ2wayOQB+mdTBcgrI3L43EK91QA1HDmX7uf/GZNBcwggmNmbvwYTvNJNBUMwZ6UxAtPoZGCDzD0/jQHihTk5gstXxrjt4WN0lt+QnrNApQ5n97WGpE9AcknAfD5dPecHwyUb0Czjjvj0wcz3/+oZtd9VY+szkvgLoYvf0AGN9KS535N+kAHDH69M5ysGFHeoytlcuhqmr7jRBOnWodVL6/geYeqn5eMxcZhOiOfX8aNVNQPxMhgTs3e/iXU/wpDIQBqGIi4QDNoauBGBvOciI1BBE=,iv:wqL8FVNmC2A6kqYnByrcKCIWgH65rXJw8sKde2IVa5w=,tag:inq22FbGe6Xqd/5CnGMl/A==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT2R4OWordERTVW5pdUdh
            OWVHelZqT0Y2Z2hjV2dXRjdKTFRqd0hHdVcwCkErVEhIaGRHc0FOdlRLNUZmUW05
            enNLUFdqYTVUMW5WSTQ5TnVwcFB5Y2sKLS0tIFBoc05MTEJuaVRxdXJqcXdva0pY
            d1RkUzkyNU5uNkZtNG1GbEJKYlhSeXcKmKS6s8nT4TcYZo4tcg2iZolU1cHBJzby
            OdVD+dhE+PgjlqL2ryU8YkuqgFpkqb8G2fFf5v7jUcr4Oq7ESbllig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T21:42:31Z"
    mac: ENC[AES256_GCM,data:VIandGyh1IYfq9dC3S2RnzGHTUG8S+yrA108fDcBTnzy5sYeVYnxIOUVgWZOMO2wYIvZZIifIjV6MpoXF1JQVEkH+l6ZrNb9IoyYEm7j97cuXyGZLsyfwH7y9aZjB7hH8M32PI5pC9k1nUEI8fIrgJJVcQsOdnd7GkXfZhAVg6E=,iv:Vty5UVxjBKa1aOA0ElTJ3a7kZojWWHT+DniRPZdM9/Y=,tag:NMmIV5vaKHGUjnxwPo+/MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
