apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-data
  namespace: glance
  labels:
    app: glance
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi