apiVersion: ENC[AES256_GCM,data:0Xk=,iv:0axW7Xd3oqnhfEXs14QMyGCEjx47OCEyhlDu50Aon1M=,tag:yYbUWaiZ3CczMn18WjNoLw==,type:str]
kind: ENC[AES256_GCM,data:W+oeCtVZ,iv:KmU6ihaSyz0x1I3Tn30TalIXLZIhjsMWdkKm1oR+HJg=,tag:6g+EY2BUE8A6nrBqk5fT7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Kll9Z+NiNbfqu7Dn+AAkbW1+G3c=,iv:K0dilIne+ij7m86IZol+ljBJ8v9jSk6HMjUdS5+ZP88=,tag:bfejiPGKNX6O0igYzaIOPw==,type:str]
    namespace: ENC[AES256_GCM,data:PyeRAkOoJTs=,iv:gVUHwoBa8yQ7FfBc33EV417qQf0lxXG9UkmyrIFKyMM=,tag:9Xj5TovYOrCv+ifLTxRYFA==,type:str]
type: ENC[AES256_GCM,data:KGbzHxjh,iv:Eqxd+YitAlaS3ul0sxSw0Uc3H/7xMj1cULe98hGbsRI=,tag:5cmGiRpzbH9fXRvboAZ6hQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:dnDGJTAWzYraU50DbLmipSZhFR42gTWn/kC0JF7WipJ4EAlK,iv:9MQ+io65xdi7M6VhweYWhTBKrMO5Nr+C0T8blcmhJjc=,tag:Rzi3NJY+TMw7tODZG2egaw==,type:comment]
    ADMIN_USERNAME: ENC[AES256_GCM,data:GCe9n+0=,iv:GgqIMk7Sag1wR/pHJzjToZuSZMDayhngRwXuN7uAKl4=,tag:xV/KCnaKs4NEd1OJvQvJQg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:CgWilo1F5oaQnW2eiNW9ZT8pQJJzOtslsS3EZP4P/GzxZAgejAW1nJ3YABU=,iv:lJzcStJFcKyJft49WKu4D7NIWBLr0z9vjlX1RzYoHK8=,tag:/2+gsDtrMq/7VfSqL4ceZQ==,type:str]
    #ENC[AES256_GCM,data:yqMncH/8m66LNMaXSE3hWP+IeQsfrNYsBSh03bLbUws23dq1J9esAE+rjtwfc+0DTw==,iv:OQcgIRuO5QOtfw/ehy3+fKA2MVb1RcW11W9Xd/Kx2iE=,tag:6LJwyKFVruH0HvIzidkfZQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:MIzTTFx7H0pPrn5xg16ZhJJO8hImWlW7+jQDrjsIO5f3a54Qz3T7Pgu4QoQAaLcTh2sBhgVoU+0uPJOTxHM6iUrwRLQDyEEI/uvld7SefLRELVVg6B+IvDFwKJDdi9ZAT+mr4/dFgRzCU36VrcedycaiL1C5zqpCYTsWM28cj/otYQ==,iv:Jn4HWawSupA9UoTBpQQgBr7GGvdd/2gZ2TkTCJ1kGeY=,tag:jF5+Xq4JwdWZTrhtBX5D8g==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT0N1ejlKaTU2N1VzWXpn
            Ty9VOUcxZjVxa25sQ3JyaC9NMXRrclFIUUNnCnhDOEZscjNWSWFod1E5UWw0QVB5
            SkFLeGF3OVJiaGNGQWxLWnFGSlVPak0KLS0tIHIvNlBxVTAxOCtpdlVPZSs3cmFt
            U1RrTElRRDk0WlVnREw4d2g3NVFmUDQKUmHV6IjosuuI7mC7lfi1hvdUmYw6YZYs
            N0CyIyqYXshKHTBJDEjDAWHt7AUSicZKsOLPvTSDaxxmLrwd+76LXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVXdnNVBwNSsxNnJGYmNs
            UGtmTzFxVkNKSCtqWEJBbzdSWDlDd2pCNkhBCkNvOU9kbklWSWttWEhoUHUzZjlZ
            dzVmdk5tdlpZbXRUc2J2TWFBOS9CSlkKLS0tIFhzTWV5WG9iVExma0QwZ3dlOWY3
            VW5HeXQ5NHBSNm1zWjc0QlVZQVN3bEkKYy/rht507BWoFASkojiyE7MrOjbQL7Cx
            Ex/Lz0wGFadATm7UaPhWZA2wMn1rR+zKoFK4fc7WwErhJna6MpL8Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T20:31:15Z"
    mac: ENC[AES256_GCM,data:Kb432WGL+ZJ/n+3XZPaYLOEdHEeETYuk6Wg+3ROcEyph9uRjby36eJ+7l/D2cCGn3MGGcIClHfyWcJed0GRlois7s+5zCZ7vMzYb/LaVoxIRTBR5WR+3Tf0MhYPQltExq89IX8Qr++rk0bQbDK3rL3NhOkSoUFPdY9lfhbq5YP0=,iv:ff5kxYVAZ8tUFtSL3jI7vQNPXNg3Jy3YhsP60vDvZlI=,tag:cOBHHDYn3ukDKq9gTCSfCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
