apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-replica-count
  namespace: longhorn-system
value: "2"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: replica-soft-anti-affinity
  namespace: longhorn-system
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-minimal-available-percentage
  namespace: longhorn-system
value: "15"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-over-provisioning-percentage
  namespace: longhorn-system
value: "200"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-data-locality
  namespace: longhorn-system
value: "best-effort"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: auto-salvage
  namespace: longhorn-system
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: node-down-pod-deletion-policy
  namespace: longhorn-system
value: "delete-both-statefulset-and-deployment-pod"