apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: sentio-systems
  namespace: sentio-systems
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcd
        email: flux@users.noreply.github.com
      messageTemplate: |
        chore(sentio): update image {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./kubernetes/clusters/home/apps/sentio-systems
    strategy: Setters
