apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - pvc.yaml
  - services.yaml
  - ingress.yaml
  # Deployments
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - deployments/keycloak.yaml
  - deployments/mosquitto.yaml
  - deployments/preprocessing.yaml
  - deployments/birder.yaml
  - deployments/speciesnet.yaml
  # ConfigMaps
  - configmaps/mosquitto.yaml
  - configmaps/keycloak-realm.yaml
  - configmaps/init-db.yaml
