apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - source.yaml
  - image-automation.yaml
  
  # ConfigMaps
  - keycloak/config-realm.yaml
  - mosquitto/config-mosquitto.yaml
  - frontend/config-nginx.yaml
  
  # HelmReleases
  - backend/helmrelease.yaml
  - frontend/helmrelease.yaml
  - keycloak/helmrelease.yaml
  - mosquitto/helmrelease.yaml
  - birder/helmrelease.yaml
  - speciesnet/helmrelease.yaml
  - preprocessing/helmrelease.yaml
  
  # Image Automation
  - backend/image-automation.yaml
  - frontend/image-automation.yaml
  - birder/image-automation.yaml
  - speciesnet/image-automation.yaml
  - preprocessing/image-automation.yaml
