apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: b8fa20b6-2c41-416b-b8fa-538a00365267
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
      - hostname: chat.syslabs.dev
        service: http://traefik.traefik.svc.cluster.local:80
      - hostname: llm.syslabs.dev
        service: http://traefik.traefik.svc.cluster.local:80
      - hostname: n8n.syslabs.dev
        service: http://traefik.traefik.svc.cluster.local:80
      - service: http_status:404
