apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm/traefik.yaml
  - helm/n8n.yaml
  - helm/postgresql.yaml
  - helm/cert-manager.yaml
  - helm/longhorn.yaml
  - helm/prometheus-community.yaml
  - helm/bitnami.yaml
  - helm/redis-operator.yaml
  - helm/tekton.yaml

