apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: sentio-redis
  namespace: sentio-systems
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
