apiVersion: ENC[AES256_GCM,data:Bgg=,iv:HjA+fa75eEaE9Sl0SxY0aqUG/9Sffis8rkiyik5qCsc=,tag:+1jtNdep2D74L7bxPvuHEw==,type:str]
kind: ENC[AES256_GCM,data:c3x1Tpga,iv:S33TPQxikZLqaP5eqrm4w85Zzfq8L+qZH8BZA47yVQ8=,tag:FZnu+brGNlse0XpzjL2BTA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1Xr6dAbJxtzMKUeH,iv:F2emTYlM9bqMJWi7frvrcwuiyWpnIZo9MfYUp/cFB8E=,tag:l4QWZ1jjr97wRtPhMvN9sA==,type:str]
    namespace: ENC[AES256_GCM,data:yGeLzj7K,iv:+SE4d9BUKXIGlh9ZsX7lCHpACgOUb5PdZPOqWRdDzig=,tag:0vRAgJB2n5BAuq1EYa1xbg==,type:str]
type: ENC[AES256_GCM,data:Am21760Q,iv:SdE/PYnpSs1etwoiPxoEumHLbDZ+x/9+D/k+m8LuU/M=,tag:gL5XRYHMIjb2t+zVVHt+pA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:bo1KPM06F37avj/9hQ/c,iv:T06towEqla/NBmpUI8DSG+I+fuOSjWsGjXJFtyX599Q=,tag:T3jMLYAxJiTp7iHgs9G5Sg==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVW9kK0dJeGQwbmFUeW9l
            VTFKM3F3SmxpSHlpZnlVNHYyVVF1N0ExV1NvCk9mWGpLaUdWcGp6M2tvUDg2Sk9D
            TjJ3QXVuV1R0SmV6WVNOM1d6MzFrVFEKLS0tIGFib212aWFkbXRJb0lYVTQzajg3
            eDBnU3JMVHpVZ2xpMzg4TXlYNGpQeW8K8IGf37m8imjVWZOdTedcUwYNOT3pXz9I
            CjOrhs2PHtp1fqL4v06LNVDx6LuNMB2Yd6Diz5d73ztosJ5uIeJI5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVUVCVGMrTzlRZmhpUkxX
            dzVNRkdKejFDVjNDenMxSkVwbTY2QVU5UURvCmwxZ2t0ZDd2OEdkN3Y4Y0hJSklH
            TDFSME1Sd295aGJIUzExNFBTSGtveU0KLS0tIExtOThyeDhHeHd0ekFPRG5CcXVC
            bHo1cHREV0xHbTVITGxHUEVCd3FzVjAK5VguB57+gD+iBUbzGnbD+ZXlbHBG6RIb
            JsAXS8nX322+HC6GM5YztXcmWo400cLcggi3etkxHig4N0jfUNIbJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T18:20:44Z"
    mac: ENC[AES256_GCM,data:Fl+9e71gyF8Zsbmdxo5ejXBpgE7/dCeQ9o2tvInRaY/hq1wlH1c2UwC6edv9BhBaB5sBBAjhp3lP2YTr0hXv4sgF0b7BEYaCvvTQi9UEZzvqm0Hbjj1/RjC922pGZhUAN2jVKjxoBOTitDsb1+1UrQ/KY9ahvH8J3RLdKSG2Yzk=,iv:aMLGIzwARW4NlbB7ndXwXJ2Rx1QThrl1yCxmedQOa5Y=,tag:up4OgRd4Fw31nu4aSFMqKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
