apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'gotify'
      routes:
      - match:
          severity: critical
        receiver: gotify
        continue: true
      - match:
          severity: warning
        receiver: gotify
        continue: true

    receivers:
    - name: 'gotify'
      webhook_configs:
      - url: 'http://gotify.gotify.svc.cluster.local/message?token=GOTIFY_TOKEN_PLACEHOLDER'
        send_resolved: true
        http_config:
          follow_redirects: true