apiVersion: ENC[AES256_GCM,data:Vt8=,iv:7LGzjEiyxHb6ijb3r0xqKbLroyrFSS1qVkkMVFBHvNs=,tag:kNqmUHXy/U0XVkQ7TLqPhQ==,type:str]
kind: ENC[AES256_GCM,data:j9XEHU2z,iv:YzRDj1RXqriWEkxqoh3ei0MslcaD4Ir4QuYUlUe6DG8=,tag:WV/eMcZ81gLvYl+W+YJPAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LccsV1yXahOeUJ1wsSxFfaeuLrzJI5I=,iv:7VPsyKvVFLgW6pDkbpm6llEqlCgRs5bKjVQAHb9zJ94=,tag:ZCZsfGtRye/BrxaT0JrfbA==,type:str]
    namespace: ENC[AES256_GCM,data:TL4mNX1lu3YWTQ==,iv:t0WEECYZfc1WixKYIxtNcBq73+cnjCNdK6cPrLnHY54=,tag:n47+awxBZJwKJ9Si6Zm7yA==,type:str]
type: ENC[AES256_GCM,data:APEPcMm9,iv:AecRD019p8qPoKpIWfkkCaWn1VW01RWcwXk7008c0EA=,tag:TVlZajc8fGW9aagNe8KkSg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:OJDLu7P2EDZhK4VmYXGyz/4EyutPwb58JW8zH6+UJLn/30K2IIAS6WG/VNsmui0y9gybk+TXgcyXd4SnazOnBx1XRdqWS4osgRzT/Dd0YSxGepAEE4osfHS1f3nVYYMtsHLMxvj/PiuO7sZOltvF0Rg/vx+lKkbYzdTZmFsPu221istwJKjL5Qu2vmO/leAbKP5Hqs4B58REB3kUQwTT3l1/kDPQ25aMBX19MBWyp7bXjPSHA09UEA==,iv:0IkJuyK4SO+61EDw5LljR75Q3ZNFwRTujiPXHPhZ4To=,tag:OzA+tYCaD4xzoUEzE59Y1g==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM1V0RHNjZ2N1U0ljd1NE
            RXFWSXpveFNQaDJIVG1RRnR0M05nQkpwNlQ4Ckh6RzdqdFBEU2lOT2tNbTc4RGRx
            cDgwb1JVaHVnbVhwRXMvRnI3T3R2R2sKLS0tIENTNmwyTmNxSTZXUjhHeWEzc2NT
            eEwwcDVVSFI4WDZjb0xZQnpBMDMzeVEKGkf99RinnkKILiL3SRLbwgExurA3rd9U
            pGgmKM9TqhC3Zs4O+U6MQMq7S6VlXoDkDjs1vgH+00XFH3xpm8mfcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwck5JSjViaU9IZmI5cmFW
            V3ZiUmdVcVR2czBWeUdSdzE0M0M4UDVqZUQ4ClVkOHlVSU9tK3lhNDFYWFFsZmp4
            WlYvQTQ3Q3EwQXgxZUxjdm44MzFGMkUKLS0tIDVpTlJkTFJnNDk4TDlMK2syQUU2
            SlhnOE9hMGVZcmp6SHVMeWhEVHZWeTQK+38mTB7Py0uKyyj7zp3W48R5G6meRLEk
            B6qM3YQuK+3UjNoM/C3NaByH1PSWKf/0VfPWwozK80ZgwXYfjpti0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T18:06:01Z"
    mac: ENC[AES256_GCM,data:FaAZAykcHdKKtp9pwwy2X65BFmibo4DEOFL8WqWB6XL27c3PFiz9ZEWGzvU4SjnRDnpm3eCmxKC9GBTadqyPFJnmX5q13Ubuoerv0BEQZKpvQDDBe7pcwCRc2fwz3qOtY4WLmT75mXsh8+fH4FC5w4pEftHCW5s2Px6Tt9+SbDs=,iv:nxePpr794ageZ9S1Is9ZDcawW4nOJtg4oEtw/xBp2W0=,tag:FaRmmVJ5KIzfLl7LEJDykg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
