apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: 69439658-da91-425c-a06c-c02bf7e5f955
    credentials-file: /etc/cloudflared/creds/tunnel-token
    
    ingress:
      # Route all traffic to Traefik
      - hostname: "*.syslabs.dev"
        service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
          httpHostHeader: "traefik.syslabs.dev"
      
      # Specific route for Traefik dashboard
      - hostname: "traefik.syslabs.dev"
        service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
          httpHostHeader: "traefik.syslabs.dev"
      
      # Catch-all rule (required)
      - service: http_status:404