apiVersion: ENC[AES256_GCM,data:xVI=,iv:1Tvi7a8Ft2KvFMXmp7U4bTGjB0Bg1onAdXyFZ6du41o=,tag:RM/nrTLHcK631lUBEUfcig==,type:str]
data:
    tunnel-token: ENC[AES256_GCM,data:rsboTRLFahxs9eHFI/EHKa/EbTIQVl/zqgrz4A4VD6N7jXyADsXcdyVptVNQ8HS44DtPV2EVFj0yVYc2svZYcH66I4FBfCGZ4zUgJEk0AImeJlzvti9I78yR9RqoHfrL2oeai+Anb1ICIAt7FtJTYECSauk7uTVCgtLN0r3jAXg7Z5QRt2PE3eY7MVn0rgOcp9UzjVeBiaiFyzI/XQ2pTrUgk6U98pH7Gpx9UOU0XOZI/a/XPJunFtjlLVhuadKlxAGRrCWK7xgDkjLrL8T3X8l32ucKjMhNPWiJRcVdNu/7UEAy0WSd9xFZtes9aLbXJvWKF1JD+BI=,iv:ohPhUaE1uOiIU9PdNv8mS8X3S6z9tW0F6dF31ZfkjWI=,tag:NCW9+zxahnNKOKsraDdr3Q==,type:str]
kind: ENC[AES256_GCM,data:8DXqWFWr,iv:a0FOBXhPIu9uGba+9krYOvdlgFTtKlwQ1Qf/Z9Vd5aM=,tag:punx2sFlOLfD4+UXgBqm+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jUqNrR3ExOQTnDGwGsT5dodKYDT/mAsu,iv:wv1cugKtlAXk2aqGmNVf/MY+QCqgKpGy7ICjHtarJCk=,tag:w03aHRGMcWDTF1zlv61U+w==,type:str]
    namespace: ENC[AES256_GCM,data:2rOPcbOpbBSdhjD5SRiX8HQ=,iv:6jijqoMo8Pg0ac1wgGr30JXl3X6IKB4f+Ki04r7Iav0=,tag:NcUBClq/MiuOMtZ3u/s6WQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OG9aTFEzNURRQjJyeHBw
            UG9sakRsYU1HQ1ZOOVZ3R2lsWGVnOXJ4NmxZClBUc0xZcWM3bWkzcDVkWkZROFlq
            UU5wczVZa05NV0lpNG9qcWovc0xLRHMKLS0tIFY1dGlyZnZNYytTbVJFeXRSYWJ1
            RTZGNVRxSS9hN3VlSGFWR3QvN3dlN2cK58+PZ+N2gjsQuGDU2tjw0n+A5UiZwPdI
            Xpm9pMg5x7CPHybj410AVQbuZsy+VLX6RicZHcyWa1jiysu7BeQQjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV3pSZlRycG8xeDhvSFFM
            TEZXYjdFM3lQNXVsTzVQcXhxK1dIYXpteURNCnJka2k3MzFlQXl2OWMxQ1ZqeFpL
            L1lJY1hnbkViZ2czSnUrb3NucldsbzgKLS0tIGZnbDdqbGl5OGUxTGN1TTk4ZkJo
            YUYzNDVoWU5hcytVMHBtdHJBcnVkV2cK7eflypkI/TB+BNkDfBuyDy2zUVblBfa0
            PbakDarghF0rb+ytSHqFDjI8jDP7yeJsb1pSg/qvte1aSVlK/alQMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T23:50:36Z"
    mac: ENC[AES256_GCM,data:t+Yn3kRlzU5w5uKcFScPwAU+qkQl/oc0m+nhecjiD5ES0ySYJG0gxINz6UAYLeK3AOz+ey6EL3Lg5uMg/Tgm1epEJ2CjfN+7gBOwtIwvB/OnvkEkaNNP95Xi+gFV0AaRRKZKwAQCe1nrcbzwOaEMMuWJd9Vm/bAsFCR2lvr/kD0=,iv:W65nF4V+qczGrjLVX7flnMePIewv26YCAJE9hE5HmAw=,tag:RIwV27F3yxH1EmbtZ+hs3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
