apiVersion: v1
kind: ConfigMap
metadata:
  name: signoz-values
  namespace: signoz
data:
  values.yaml: |
    global:
      storageClass: longhorn

    clickhouse:
      installCustomStorageClass: true
