apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "28.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 2
    service:
      type: LoadBalancer
    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 80
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        tls:
          enabled: true
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--providers.kubernetescrd"
      - "--providers.kubernetesingress"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    persistence:
      enabled: true
      size: 128Mi
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 150Mi