#ENC[AES256_GCM,data:UK14dzm1X86t6yAENYVY5dLjb7o9xh2YrNm0hkKLBbTnD09FvZ9fVDBiwk2YAx4RCsABLp/btA==,iv:rGce0wDUyqDR6pKlyvB3cawAKK5jkg+GpuDC3jTznfM=,tag:aauosfRJZw4CEdloZzc2fQ==,type:comment]
#ENC[AES256_GCM,data:A402tZe59OzUuvwy65x5/So9pjK3zXniY+SnceT5D8wILdawM46JG5HFSfl4fyjsG2HFjsuNJxJ+UJ4NHlvc,iv:FYB0jiF3a0TB4QL8ISvUD/1m94XHJ7RN9l34uampLqM=,tag:aBCcPxaF1vDQTX6o7Jkawg==,type:comment]
apiVersion: ENC[AES256_GCM,data:lvM=,iv:vJaJWOiZevPNs9qs3hMOOn9mZmijHE8arYE4VQgN5WU=,tag:njK+uBWKe1Q3Q5d9rN6QlQ==,type:str]
kind: ENC[AES256_GCM,data:fF4dOJzZ,iv:XbcXlgBIOvdOa6b5SYWpY0yFny3sA4qJcsE+NAb0Pqw=,tag:Y+k9Wf3aiDNjaf0TjP+x6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oj/+HYUjHKHYPTRmXY/OdJyw,iv:sicPXisznn9Tu/BjZucvqpxSFp7clwxJDBlkOR1qalk=,tag:TnYE4YfAnrpCDGIPn0kBcw==,type:str]
    namespace: ENC[AES256_GCM,data:wudab2x5FKJQAg==,iv:JF53uHsp0jtdD1LOwLTnDhY6ivV/JvqbXlhQVj+K+nQ=,tag:R+hqMHCS57YPzJMmu6AL9g==,type:str]
type: ENC[AES256_GCM,data:SU1Poimn,iv:X+y0TovD5leFUoOgFJugQ05k5BFeWkd/sQM9nzJXDnk=,tag:uMQmcNGrEJM5wCHNUP0Lhg==,type:str]
stringData:
    #ENC[AES256_GCM,data:lu+q/84/NEtSiNz9tmKN/e23q5zPsjtN4E/DqAmw/TfKd7s46nY6wyFT7M4mg+/f6IEzCZEBdCxocCZX6o4RAYe6kKciHQr0rsUVUWjaK0s=,iv:SzcIriWOM/uhW5PaW2WbbuY/xZhRh093x8jFqebykpo=,tag:sJsEtLJ6DedodbpCo+4zIQ==,type:comment]
    #ENC[AES256_GCM,data:FqTcLdXlSsPIEl1bqw3RdZK53dB6mArN3RYpGirMIssJ,iv:qnD1crCJp+Wpv0d94Ld/gZhtCWSBsmwVTDnSwajdD5A=,tag:RRIviPKV/B+8rA2+pVzuqA==,type:comment]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:qDnssDGFOjlouGqUfPupOiovBwQ+h98g/heF7V7H0V64IQ4liZWK+iblYjMV/ayj8RRqMy7WOxpGzGjMj0uI1BurgUYA34MIex0yxP3tk58dD5Sg4fFkobQz8quum1/xOqOFjzG3nxXiMssuy04k7JpiyrdzYETe1rr8MTSCT2Z5HKD2ghLTUJ2TU9mUz78sjhvOFYHR8qK6o482u1rX+F5g8JL+PDVf6qvQ+0XCWBiM/i7gDigVqA==,iv:MCn5ZE2fdjVLi7mYwM7TkBTOgyiBeCgA7yMvSUQ7YxQ=,tag:0d7XkZhVWfR0L+skrYGREQ==,type:str]
    #ENC[AES256_GCM,data:6FEWuVHXqQnYLKnuCfPLPwtnjZnFbAimAk+Eu7qac9JxFXWzZb1WE9xy35IBYh/E5VfcOwsqMZQPzbY8CQMvw5KS2S9ImTeWJXqZV6Q7bCRsK6Ci,iv:AyT7Hj34oU1qRy0BIgjB8xwDV+KWeH+FOY/BB/wA8vY=,tag:cnrYFs9rtES7duGEAlDUHA==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:5ei6UZNXbkVciNxIr6wokE6GHm/23Towv8aVxBW/+a+GAfABPRUAjQ==,iv:IxOAQRyIq9Y23TxejWhMaq0yO6f2jeegaCAi9G1ljss=,tag:B+XEw60Gzo6rCcGGo5NNng==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMkoxRW53MW1qcFdmWll0
            ZHA1dmo3S2hoUzBWUGhXMUxEUUdxZkRPMGpZCmFFL1dtdHlySFhpS0tpVG56dHVj
            bWtVc2hZVlZPU3p3SGI1TGNWZzllRXMKLS0tIFVGRSsyVlJrODVqMnJoMk5Wc2p4
            VWlGUUZqK2Y1bU9HNCs3QnRkcjArbEUKnIRLYH6HGGwdvfrMPsFZ0tDp7sAciu/9
            fsqFvDQKZ9dfUSKq6FcodkMfZaUOKjgk95VrjufyfAsv+rFXDGgMaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s0zny37a6hm00kefeq3q9swjw0prd0urzctzpsq2wqznxxpkpesukfd4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUmR3SGY4U3lPK1FLbm9O
            eTRtUXZNZGFJM2VaR3NzbHZ2Z1haQVdKbVdVClpvNGo4RTRIZGhFY0kxMUdLbmo3
            ZElwMG4wUGIvWEFwdDhCN1Q4aW9vT2cKLS0tIFJhczJtVXltVHM3Y0dWL3ZFcmdY
            T3d1ZVJyRytJRnhDVyt5YlNPdzVJcVkK1vndwm9pwGGwJk03wDdmECmpqaS6KOoo
            l5OT7a82AkVBmTmCnIPbyMIl7RZjwqGCdVllhTlPWDXcy2zl+qcD8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T19:48:56Z"
    mac: ENC[AES256_GCM,data:PnOM13GlASByBMVLkYn2wx9Z6SC4zY4IDPGOOUmWFcNH0EVg+t7IQgz216BJIr1xLYk9RlV55AIrh6q7SsnKg44KtOmQ3jthpPptHmyRBC10fEy/xUUtuqF513DbFr+8nkysGKqiOBGMKTqz10IZwcgVjrHlNInhjZY4FssoEik=,iv:MGgxZ2/v6y8Tq2mMXc/sPabupMFWIaGrC4zNnL1vmzw=,tag:HuvH+Ye8uKj9X06EhPRqtg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
