apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
  namespace: netbird
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: netbird
      version: "0.4.2"
      sourceRef:
        kind: HelmRepository
        name: netbird
        namespace: flux-system
  values:
    server:
      config:
        exposedAddress: "https://netbird.syslabs.dev:443"
        auth:
          issuer: "https://netbird.syslabs.dev/oauth2"
          dashboardRedirectURIs:
            - "https://netbird.syslabs.dev/nb-auth"
            - "https://netbird.syslabs.dev/nb-silent-auth"
      secrets:
        storeEncryptionKey:
          secretName: "netbird-helm-values"
          secretKey: "encryptionKey"
          autoGenerate: false
        authSecret:
          secretName: "netbird-helm-values"
          secretKey: "authSecret"
          autoGenerate: false
      stunService:
        type: ClusterIP
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    oidc:
      enabled: true
      idpManager:
        enabled: true
        managerType: "embedded"
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
