apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentio-frontend
  namespace: sentio-prod
  labels:
    app: sentio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentio-frontend
  template:
    metadata:
      labels:
        app: sentio-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: frontend
          image: ghcr.io/lucawalz/sentio-systems/sentio-web:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: "" 
            - name: VITE_KEYCLOAK_URL
              value: "https://sentio.syslabs.dev/auth"
            - name: VITE_KEYCLOAK_REALM
              value: "sentio"
            - name: VITE_KEYCLOAK_CLIENT_ID
              value: "sentio-web"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
