apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentio-shared-images
  namespace: sentio-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
