apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sentio-frontend
  namespace: sentio-systems
spec:
  image: ghcr.io/lucawalz/sentio-systems/sentio-web
  interval: 1m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sentio-frontend
  namespace: sentio-systems
spec:
  imageRepositoryRef:
    name: sentio-frontend
  policy:
    semver:
      range: '>=0.0.0-0'  # Matches all semver tags including pre-releases
