apiVersion: v1
kind: Service
metadata:
  name: sentio-speciesnet-ai
  namespace: sentio-staging
spec:
  selector:
    app: sentio-speciesnet-ai
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
