apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-data
  namespace: netdata
  labels:
    app: netdata
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi