apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: sentio-cicd
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: github-push
      bindings:
        - ref: github-push-binding
      template:
        ref: sentio-pipeline-template
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ["push"]
