apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sentio-pipeline-template
  namespace: sentio-cicd
spec:
  params:
    - name: git-revision
    - name: git-url
    - name: git-branch
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sentio-run-
        namespace: sentio-cicd
      spec:
        serviceAccountName: tekton-sa
        pipelineRef:
          name: sentio-build-deploy
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
          - name: infra-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
